config/routes.rb
Rails.application.routes.draw do

  root :to => 'pages#index'
  get '/home', to: 'pages#home'
  get '/dashboard', to: 'pages#dashboard'
  get '/catalog', to: 'pages#catalog'
  get '/orders', to: 'pages#orders'
  get '/contacts', to: 'pages#contacts'
  get '/friends', to: 'pages#friends'
  get '/profile', to: 'pages#profile'
  get '/profile_edit', to: 'pages#profile_edit'
  get '/sign_in', to: 'pages#sign_in'
  get '/sign_up', to: 'pages#sign_up'
  get '/forgot_password', to: 'pages#forgot_password'
  get '/reset_password', to: 'pages#reset_password'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # Consts
  # Template
  SITE_TAB_NAME = 'Название закладки'
  SITE_HEADER_NAME = 'Название сайта'
  SITE_HEADER_TEXT = 'Дополнительный текст'
  SITE_HEADER_LOGO_URL = '/images/template/logo.png'
  # Users
  USER_ADMIN = "admin"
  USER_EDITOR = "editor"
  USER_AUTHOR = "author"
  USER_BUYER = "buyer"
  USER_GUEST = "guest"
  # Goals
  USER_GOAL = "Выберите цель регистрации"
  USER_AUTHOR_GOAL = "Размещение материала"
  USER_BUYER_GOAL = "Покупка, инвестирование"
  
  helper_method :is_admin?, :is_editor?, :is_author?, :is_buyer?, :is_guest?

  def is_admin? (user)
  	user == USER_ADMIN
  end

  def is_editor? (user)
  	user == USER_EDITOR
  end

  def is_author? (user)
  	user == USER_AUTHOR
  end

  def is_buyer? (user)
  	user == USER_BUYER
  end

  def is_guest? (user)
  	user == USER_GUEST
  end  

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  	
  end

  def home
  	@user = params[:user]
  end	

  def dashboard
  	@user = params[:user]
  end

  def catalog
  	@user = params[:user]
  end	

  def orders
  	@user = params[:user]
  end

  def contacts
  	@user = params[:user]
  end

  def friends
  	@user = params[:user]
  end

  def profile
  	@user = params[:user]
  end

  def profile_edit
    @user = params[:user]
  end

  def sign_in
  	@user = params[:user]
  end	

  def sign_up
    @user = params[:user]
    @goals = ApplicationController::USER_AUTHOR_GOAL,ApplicationController::USER_BUYER_GOAL
  end 

  def forgot_password
    @user = params[:user]
  end 

  def reset_password
    @user = params[:user]
  end 


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.slim
footer
  p.footer_text Авторские права © 2016
  p.footer_text Все права защищены.

app/views/layouts/_header.slim
header
  div
    = link_to (image_tag (ApplicationController::SITE_HEADER_LOGO_URL), id: "header-logo"), root_url
    
    #header-text
      p.header-main-text = ApplicationController::SITE_HEADER_NAME
      p.header-add-text = ApplicationController::SITE_HEADER_TEXT

app/views/layouts/_menu.slim
ul.menu.row
  - if is_admin? (@user) or is_editor? (@user) or is_author? (@user) or is_buyer? (@user) or is_guest? (@user)
    li.control-left = link_to "Домашняя страница", home_path(:user => @user)
  - if is_admin? (@user) or is_editor? (@user)
    li.control-left = link_to "Активы сайта", dashboard_path(:user => @user) 
  - if is_admin? (@user) or is_editor? (@user) or is_author? (@user) or is_buyer? (@user) or is_guest? (@user)  
    li.control-left = link_to "Каталог", catalog_path(:user => @user)
  - if is_admin? (@user) or is_editor? (@user)
    li.control-left = link_to "Заказы", orders_path(:user => @user)
  - if is_admin? (@user) or is_editor? (@user) or is_author? (@user) or is_buyer? (@user) or is_guest? (@user)   
    li.control-left = link_to "Контакты", contacts_path(:user => @user)
  - if is_admin? (@user) or is_editor? (@user) or is_author? (@user) or is_buyer? (@user) or is_guest? (@user)
    li.control-left = link_to "Дружественные сайты", friends_path(:user => @user) 
  
  - if is_admin? (@user) or is_editor? (@user) or is_author? (@user) or is_buyer? (@user)
    li.control-right =link_to "Выход", root_path 
    li.control-right =link_to "Личный кабинет", profile_path(:user => @user)    
  - else 
    - if is_guest? (@user)  
      li.control-right =link_to "Вход", sign_in_path(:user => @user) 
    

app/views/layouts/application.html.slim
doctype html
html
  head
    title = ApplicationController::SITE_TAB_NAME
    = favicon_link_tag "favicon.ico"
    = stylesheet_link_tag    "application", :media => "all" 
    = javascript_include_tag "application" 
    = csrf_meta_tags 

  body 
    .container
      = render 'layouts/header'
      = render 'layouts/menu'
      div
        == yield
      .clear
      = render "layouts/footer" 
    

app/views/pages/catalog.html.slim
h1 Каталог

app/views/pages/contacts.html.slim
h1 Контакты

app/views/pages/dashboard.html.slim
h1 Активы сайта

app/views/pages/forgot_password.html.slim
div
  div.user-form
    h2 Восстановление пароля

    = form_for @user do |f|
      = f.text_field nil, class: "input-user", placeholder: "Логин"  
    
    div.footer-btn
      .btn.control-right
        =link_to "Восстановить", reset_password_path(:user => @user)
      
      = link_to "Регистрация", sign_up_path(:user => @user), class: 'control-left' 

app/views/pages/friends.html.slim
h1 Дружественные сайты

app/views/pages/home.html.slim
h1 Домашняя страница

img.right-img src="/images/home-page/image1.jpg" 
p.page-text Каждый веб-разработчик знает, что такое текст-«рыба». Текст этот, несмотря на название, не имеет никакого отношения к обитателям водоемов. Используется он веб-дизайнерами для вставки на интернет-страницы и демонстрации внешнего вида контента, просмотра шрифтов, абзацев, отступов и т.д. Так как цель применения такого текста исключительно демонстрационная, то и смысловую нагрузку ему нести совсем необязательно. Более того, нечитабельность текста сыграет на руку при оценке качества восприятия макета. Самым известным «рыбным» текстом является знаменитый Lorem ipsum. Считается, что впервые его применили в книгопечатании еще в XVI веке. Своим появлением Lorem ipsum обязан древнеримскому философу Цицерону, ведь именно из его трактата «О пределах добра и зла» средневековый книгопечатник вырвал отдельные фразы и слова, получив текст-«рыбу», широко используемый и по сей день. Конечно, возникают некоторые вопросы, связанные с использованием Lorem ipsum на сайтах и проектах, ориентированных на кириллический контент – написание символов на латыни и на кириллице значительно различается. И даже с языками, использующими латинский алфавит, могут возникнуть небольшие проблемы: в различных языках те или иные буквы встречаются с разной частотой, имеется разница в длине наиболее распространенных слов. Отсюда напрашивается вывод, что все же лучше использовать в качестве «рыбы» текст на том языке, который планируется использовать при запуске проекта. Сегодня существует несколько вариантов Lorem ipsum, кроме того, есть специальные генераторы, создающие собственные варианты текста на основе оригинального трактата, благодаря чему появляется возможность получить более длинный неповторяющийся набор слов.

app/views/pages/index.html.slim
h1 Список страниц

div.row
  div.index-menu-block.control-left.rounded
    h3 Домашняя страница
    ul.clear-markers
      li = link_to "Домашняя страница - Администратор", home_path(:user => ApplicationController::USER_ADMIN)
	  li = link_to "Домашняя страница - Редактор", home_path(:user => ApplicationController::USER_EDITOR)
	  li = link_to "Домашняя страница - Автор", home_path(:user => ApplicationController::USER_AUTHOR)
	  li = link_to "Домашняя страница - Покупатель", home_path(:user => ApplicationController::USER_BUYER)
	  li = link_to "Домашняя страница - Гость", home_path(:user => ApplicationController::USER_GUEST)

  div.index-menu-block.control-left.rounded
    h3 Активы сайта
    ul.clear-markers
      li = link_to "Активы сайта - Администратор", dashboard_path(:user => ApplicationController::USER_ADMIN)
	  li = link_to "Активы сайта - Редактор", dashboard_path(:user => ApplicationController::USER_EDITOR)

  div.index-menu-block.control-left.rounded
    h3 Каталог
    ul.clear-markers
      li = link_to "Каталог - Администратор", catalog_path(:user => ApplicationController::USER_ADMIN)
	  li = link_to "Каталог - Редактор", catalog_path(:user => ApplicationController::USER_EDITOR)
	  li = link_to "Каталог - Автор", catalog_path(:user => ApplicationController::USER_AUTHOR)
	  li = link_to "Каталог - Покупатель", catalog_path(:user => ApplicationController::USER_BUYER)
	  li = link_to "Каталог - Гость", catalog_path(:user => ApplicationController::USER_GUEST)

  div.index-menu-block.control-left.rounded
    h3 Заказы
    ul.clear-markers
      li = link_to "Заказы - Администратор", orders_path(:user => ApplicationController::USER_ADMIN)
	  li = link_to "Заказы - Редактор", orders_path(:user => ApplicationController::USER_EDITOR)

  div.index-menu-block.control-left.rounded
    h3 Контакты
    ul.clear-markers
      li = link_to "Контакты - Администратор", contacts_path(:user => ApplicationController::USER_ADMIN)
	  li = link_to "Контакты - Редактор", contacts_path(:user => ApplicationController::USER_EDITOR)
	  li = link_to "Контакты - Автор", contacts_path(:user => ApplicationController::USER_AUTHOR)
	  li = link_to "Контакты - Покупатель", contacts_path(:user => ApplicationController::USER_BUYER)
	  li = link_to "Контакты - Гость", contacts_path(:user => ApplicationController::USER_GUEST)

  div.index-menu-block.control-left.rounded
    h3 Дружественные сайты
    ul.clear-markers
      li = link_to "Дружественные сайты - Администратор", friends_path(:user => ApplicationController::USER_ADMIN)
	  li = link_to "Дружественные сайты - Редактор", friends_path(:user => ApplicationController::USER_EDITOR)
	  li = link_to "Дружественные сайты - Автор", friends_path(:user => ApplicationController::USER_AUTHOR)
	  li = link_to "Дружественные сайты - Покупатель", friends_path(:user => ApplicationController::USER_BUYER)
	  li = link_to "Дружественные сайты - Гость", friends_path(:user => ApplicationController::USER_GUEST)

  div.index-menu-block.control-left.rounded
    h3 Личный кабинет
    ul.clear-markers
      li = link_to "Личный кабинет - Администратор", profile_path(:user => ApplicationController::USER_ADMIN)
	  li = link_to "Личный кабинет - Редактор", profile_path(:user => ApplicationController::USER_EDITOR)
	  li = link_to "Личный кабинет - Автор", profile_path(:user => ApplicationController::USER_AUTHOR)
	  li = link_to "Личный кабинет - Покупатель", profile_path(:user => ApplicationController::USER_BUYER)
	  

app/views/pages/orders.html.slim
h1 Заказы

app/views/pages/profile.html.slim
h1 Личный кабинет

div.row
  - if is_admin? (@user) or is_editor? (@user) or is_author? (@user) or is_buyer? (@user)
    div.control-left.rounded.profile-menu
      img.profile-menu-img src="/images/home-page/image1.jpg" 
      =link_to "Редактировать учётную запись", profile_edit_path(:user => @user)

app/views/pages/profile_edit.html.slim
h1 Редактирование учётной записи

div.row
  div.control-left
	h3 Контактное лицо

	div.control-left
	  img.avatar-img src="/images/home-page/image1.jpg" 

	div.control-left
	  = form_for @user do |f|
	    = f.text_field nil, class: "input-user", placeholder: "Ф.И.О."
	    br  
	    = f.text_field nil, class: "input-user", placeholder: "Логин"  
	    br  
	    = f.text_field nil, class: "input-user", placeholder: "Контактный телефон" 
	    br
	    = f.text_field nil, class: "input-user", placeholder: "Skype" 

  div.control-left
    h3 Организация

	div.control-left
	  img.avatar-img src="/images/home-page/image1.jpg" 

	div.control-left
	  = form_for @user do |f|
	    = f.text_field nil, class: "input-user", placeholder: "Название"
	    br  
	    = f.text_field nil, class: "input-user", placeholder: "УНН"  
	    br  
	    = f.text_field nil, class: "input-user", placeholder: "Адрес" 
	    br
	    = f.text_field nil, class: "input-user", placeholder: "Почтовый индекс" 
	    br
	    = f.text_field nil, class: "input-user", placeholder: "Телефон" 

div
  .btn.control-right
    =link_to "Сохранить", home_path(:user => @user)

app/views/pages/reset_password.html.slim
div
  div.user-form
    h2 Новый пароль

    = form_for @user do |f|
      = f.password_field nil, class: "input-user", placeholder: "Пароль"  
      = f.password_field nil, class: "input-user", placeholder: "Подтверждение пароля"  
    
    div.footer-btn
      .btn.control-right
        =link_to "Сохранить", reset_password_path(:user => @user)

app/views/pages/sign_in.html.slim
div
  div.user-form
    h2 Вход в личный кабинет

    = form_for @user do |f|
      = f.text_field nil, class: "input-user", placeholder: "Логин"  
      = f.password_field nil, class: "input-user", placeholder: "Пароль"  
    
    div.footer-btn
      .btn.control-right
        =link_to "Войти", profile_path(:user => ApplicationController::USER_AUTHOR)
      
      = link_to "Регистрация", sign_up_path(:user => @user), class: 'control-left' 
      = link_to "Забыли пароль?", forgot_password_path(:user => @user), class: 'control-left' 

app/views/pages/sign_up.html.slim
div
  div.user-form
    h2 Регистрация

	= form_for @user do |f|
      = f.text_field nil, class: "input-user", placeholder: "Логин"  
      = f.password_field nil, class: "input-user", placeholder: "Пароль"  
      = f.password_field nil, class: "input-user", placeholder: "Подтверждение пароля"  
      = f.select nil, @goals, { include_blank: ApplicationController::USER_GOAL }, { class: 'dropdown-user' }

    div.footer-btn
      .btn.control-right
        =link_to "Регистрация", home_path(:user => ApplicationController::USER_AUTHOR)

      = link_to "Забыли пароль?", forgot_password_path(:user => @user), class: 'control-left'   